// <auto-generated />
using System;
using FasterNFaster.Api.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FasterNFaster.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260316183236_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FasterNFaster.Api.Core.Entities.CommentThreshold", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("comment_text");

                    b.Property<int>("CooldownSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("cooldown_seconds");

                    b.Property<double>("MaxWpm")
                        .HasColumnType("double precision")
                        .HasColumnName("max_wpm");

                    b.Property<double>("MinWpm")
                        .HasColumnType("double precision")
                        .HasColumnName("min_wpm");

                    b.HasKey("Id");

                    b.ToTable("comment_thresholds");
                });

            modelBuilder.Entity("FasterNFaster.Api.Core.Entities.Lobby", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GameMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("game_mode");

                    b.Property<Guid?>("HostPlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_player_id");

                    b.Property<string>("InviteCode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("invite_code");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean")
                        .HasColumnName("is_private");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("integer")
                        .HasColumnName("max_players");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("InviteCode")
                        .IsUnique()
                        .HasFilter("\"invite_code\" IS NOT NULL");

                    b.ToTable("lobbies");
                });

            modelBuilder.Entity("FasterNFaster.Api.Core.Entities.LobbyPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConnectionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("connection_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsConnected")
                        .HasColumnType("boolean")
                        .HasColumnName("is_connected");

                    b.Property<int>("JoinOrder")
                        .HasColumnType("integer")
                        .HasColumnName("join_order");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<Guid>("LobbyId")
                        .HasColumnType("uuid")
                        .HasColumnName("lobby_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("LobbyId");

                    b.ToTable("lobby_players");
                });

            modelBuilder.Entity("FasterNFaster.Api.Core.Entities.RaceResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("Accuracy")
                        .HasColumnType("double precision")
                        .HasColumnName("accuracy");

                    b.Property<int>("FinishPosition")
                        .HasColumnType("integer")
                        .HasColumnName("finish_position");

                    b.Property<DateTime>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<double>("GrossWpm")
                        .HasColumnType("double precision")
                        .HasColumnName("gross_wpm");

                    b.Property<Guid>("LobbyId")
                        .HasColumnType("uuid")
                        .HasColumnName("lobby_id");

                    b.Property<Guid>("LobbyPlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("lobby_player_id");

                    b.Property<int>("MistakeCount")
                        .HasColumnType("integer")
                        .HasColumnName("mistake_count");

                    b.Property<double>("NetWpm")
                        .HasColumnType("double precision")
                        .HasColumnName("net_wpm");

                    b.HasKey("Id");

                    b.HasIndex("LobbyId");

                    b.HasIndex("LobbyPlayerId");

                    b.ToTable("race_results");
                });

            modelBuilder.Entity("FasterNFaster.Api.Core.Entities.LobbyPlayer", b =>
                {
                    b.HasOne("FasterNFaster.Api.Core.Entities.Lobby", "Lobby")
                        .WithMany("Players")
                        .HasForeignKey("LobbyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lobby");
                });

            modelBuilder.Entity("FasterNFaster.Api.Core.Entities.RaceResult", b =>
                {
                    b.HasOne("FasterNFaster.Api.Core.Entities.Lobby", "Lobby")
                        .WithMany("RaceResults")
                        .HasForeignKey("LobbyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FasterNFaster.Api.Core.Entities.LobbyPlayer", "LobbyPlayer")
                        .WithMany("RaceResults")
                        .HasForeignKey("LobbyPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lobby");

                    b.Navigation("LobbyPlayer");
                });

            modelBuilder.Entity("FasterNFaster.Api.Core.Entities.Lobby", b =>
                {
                    b.Navigation("Players");

                    b.Navigation("RaceResults");
                });

            modelBuilder.Entity("FasterNFaster.Api.Core.Entities.LobbyPlayer", b =>
                {
                    b.Navigation("RaceResults");
                });
#pragma warning restore 612, 618
        }
    }
}
