// <auto-generated />
using System;
using FasterNFaster.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FasterNFaster.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260326103243_AddPlayerStatistics")]
    partial class AddPlayerStatistics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FasterNFaster.Api.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Login")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nick")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PlayerStatistics", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<float>("AvgAccuracy")
                        .HasColumnType("real");

                    b.Property<float>("AvgWPM")
                        .HasColumnType("real");

                    b.Property<float>("BestAccuracy")
                        .HasColumnType("real");

                    b.Property<float>("BestWPM")
                        .HasColumnType("real");

                    b.Property<int>("RacesTyped")
                        .HasColumnType("integer");

                    b.Property<float>("SumAccuracy")
                        .HasColumnType("real");

                    b.Property<float>("SumWPM")
                        .HasColumnType("real");

                    b.Property<int>("SymbolsTyped")
                        .HasColumnType("integer");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.Property<int>("WordsTyped")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Statistics");
                });

            modelBuilder.Entity("PlayerStatistics", b =>
                {
                    b.HasOne("FasterNFaster.Api.Core.Entities.User", "User")
                        .WithOne("Statistics")
                        .HasForeignKey("PlayerStatistics", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FasterNFaster.Api.Core.Entities.User", b =>
                {
                    b.Navigation("Statistics");
                });
#pragma warning restore 612, 618
        }
    }
}
