name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend-build:

    runs-on: ubuntu-latest
    
    env:
      Solution_name: fasternfaster.api/FasterNFaster.Api.sln
      Test_project_path: fasternfaster.tests/FasterNFaster.Tests.csproj
      Api_project_path: fasternfaster.api/FasterNFaster.Api.csproj
      Api_project_name: FasterNFaster.Api.csproj
      
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore  ${{ env.Solution_name }}
    - name: Build
      run: dotnet build  ${{ env.Solution_name }} --no-restore
    - name: Test
      run: dotnet test  ${{ env.Test_project_path }} --no-build --verbosity normal

  frontend-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: fasternfasterapp
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: npm
        cache-dependency-path: fasternfasterapp/package-lock.json
    - run: npm ci --legacy-peer-deps
    - run: npm run build
