name: CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      Solution_name: FasterNFaster.Api.sln
      Test_project_path: fasternfaster.tests/FasterNFaster.Tests.csproj
      Api_project_path: fasternfaster.api/FasterNFaster.Api.csproj
      
      
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore $Api_project_path
    - name: Build
      run: dotnet build $Api_Project_path --no-restore
    - name: Test
      run: dotnet test $Test_project_path --no-build --verbosity normal
